travis:
  secure:
    BINSTAR_TOKEN: gyXjfs1KPbuLQQ6RInZ9nJmihPZadnNKfees9TOPwT1Ald4C25f6YFBo2cUPbzWT2FYewyq5mBAHkgKmRS1cqKimIDIdLea8SdUuW6nS3SijsnvWafvx+403Q11lUV3/qYqW3agY+/DfU7WblRnNv4aisZnszIfgMLecJxVF33BYG5RPadMGWKEaAWygAK0C6DOS1Jsau/gnrr/a0Y+zQb5Xu0A6yB4rEvldKB6+Ep7YWHiVPm60Utp2w0BiLuvQcmiUO/yZaUehS5ec0ZeW2H2tyDHhHL4u0hu4fj5uoaOidx//23scwLF3JkWGXIpbN8pes0ytXDXmzLicUIvUJr+snAN2EevdJCb1rijk1j5NLxnsVBYflkmQYo+fh0bivRhkpJgf1lPxSphZH5Hg2HSiUPRa8dHkb7vid4vaACqm0ZE7NL975BY3CPSeIDRAf0Ego18lpmPj4xNWMuxiHcEf3p/nXP2Vcpbzj4sPQNLudFJbwcgRPMT/wwTHXLLyJ1K2FonTx+j+nqgJYW88y6CyfdxTXmNmQBfRcxxc1wcdrS+2dztGh+g9LNT/hvewU8J+ebKO/v6bb1vZnqj2yoUEUMyW0tjT3j75jM/j+nQdWilkVZBCHJX6638DdhaTS8pSHoO/NNk8TNSITKl6BbY0ADi5eTKXKxRREnx87M0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
